name: k_login
description: "A new Flutter login."
version: 0.0.1
homepage: https://github.com/yaooort/k_login

environment:
  sdk: ^3.7.0
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  another_flushbar: ^1.10.29
  another_transformer_page_view: ^2.0.0
  intl_phone_number_input: ^0.7.4
  phone_numbers_parser: ^9.0.3
  provider: ^6.1.2
  quiver: ^3.2.2
  sign_in_button: ^3.2.0
  url_launcher: ^6.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

